# Generated by Django 3.2.11 on 2022-01-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='upload_method',
        ),
        migrations.AddField(
            model_name='file',
            name='upload_author',
            field=models.CharField(default='Student', max_length=10, verbose_name='Upload Author'),
        ),
    ]
