# Generated by Django 3.2.11 on 2022-01-21 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20220120_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='author',
            field=models.CharField(max_length=20, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(null=True, upload_to=models.DateField(default=datetime.date.today, verbose_name='日期'), verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='role',
            field=models.CharField(choices=[('Coach', '教练'), ('Competitor', '选手'), ('Student', '学生')], default='Student', max_length=10, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='title',
            field=models.CharField(choices=[('class', '第46届世界技能大赛网络系统管理项目精英班训练日志'), ('training', '第46届世界技能大赛网络系统管理项目中国集训队集训日志')], default='class', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
