# Generated by Django 3.2.11 on 2022-01-26 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20220121_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='role',
            new_name='author_role',
        ),
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='title',
            new_name='class_type',
        ),
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='date',
            new_name='log_date',
        ),
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='uploaded_at',
            new_name='uploaded_date',
        ),
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='log_file',
            field=models.FileField(null=True, upload_to=datetime.date, verbose_name='文件'),
        ),
    ]
