# Generated by Django 3.2.11 on 2022-01-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20220126_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfilemodel',
            options={'ordering': ('-uploaded_date',)},
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='module_list',
            field=models.CharField(choices=[('A', 'A模块: ServerClient'), ('B', 'B模块: Network'), ('C', 'C模块: Python'), ('D', 'D模块: TroubleShooting'), ('E', 'E模块: English'), ('Other', 'Other')], default='A', max_length=100, verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='author_name',
            field=models.CharField(max_length=10, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='author_role',
            field=models.CharField(choices=[('Coach', '教练'), ('Competitor', '选手'), ('Student', '学生')], default='Competitor', max_length=10, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='class_type',
            field=models.CharField(choices=[('class', '第46届世界技能大赛网络系统管理项目精英班训练日志'), ('training', '第46届世界技能大赛网络系统管理项目中国集训队集训日志')], default='training', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='log_file',
            field=models.FileField(help_text='只能上传doc, docx, pdf格式的文件。', null=True, upload_to='upload/', verbose_name='文件'),
        ),
    ]
