# Generated by Django 3.2.11 on 2022-02-09 09:28

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20220126_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfilemodel',
            options={'ordering': ('-log_date', '-uploaded_date')},
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='class_type',
            field=models.CharField(choices=[('CL', '第46届世界技能大赛网络系统管理项目精英班训练日志'), ('TR', '第46届世界技能大赛网络系统管理项目中国集训队集训日志')], default='training', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='log_file',
            field=models.FileField(help_text='只能上传doc, docx, pdf格式的文件。', null=True, upload_to=upload.models.user_dierctory_path, verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='module_list',
            field=models.CharField(choices=[('ModuleA', 'A模块: ServerClient'), ('ModuleB', 'B模块: Network'), ('ModuleC', 'C模块: Python'), ('ModuleD', 'D模块: TroubleShooting'), ('ModuleE', 'E模块: English'), ('Other', 'Other')], default='A', max_length=100, verbose_name='模块'),
        ),
    ]
