# Generated by Django 3.2.11 on 2022-02-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20220209_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='class_type',
            field=models.CharField(choices=[('CL', '网管精英班'), ('TR', '中国集训队')], default='CL', max_length=100, verbose_name='标题'),
        ),
    ]
