# Generated by Django 3.2.11 on 2022-02-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_alter_uploadfilemodel_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='class_type',
            field=models.CharField(choices=[('CL', '精英班'), ('TR', '中国集训队')], default='TR', max_length=100, verbose_name='标题'),
        ),
    ]
