# Generated by Django 3.2.11 on 2022-02-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_alter_uploadfilemodel_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='class_type',
            field=models.CharField(choices=[('CL', '精英班'), ('TR', '中国集训队')], default='TR', max_length=100, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='module_list',
            field=models.CharField(choices=[('ModuleA', 'A模块: ServerClient'), ('ModuleB', 'B模块: Network'), ('ModuleC', 'C模块: Python'), ('ModuleD', 'D模块: TroubleShooting'), ('ModuleE', 'E模块: English'), ('Other', 'Other')], default='ModuleA', max_length=100, verbose_name='模块'),
        ),
    ]
