# Generated by Django 3.2.11 on 2022-02-09 12:40

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_alter_uploadfilemodel_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='log_file',
            field=models.FileField(help_text='只能上传doc, docx, pdf格式的文件。', storage=upload.models.OverwriteStorage(), upload_to=upload.models.user_dierctory_path, verbose_name='文件'),
        ),
    ]
